// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { defineConfig } from "prisma/config";

// `prisma generate` only needs a parseable URL (Vercel/CI may not inject DATABASE_URL at generate time).
// Runtime queries still require a real DATABASE_URL via lib/prisma.ts.
const datasourceUrl =
  process.env.DATABASE_URL ??
  "postgresql://build:build@127.0.0.1:5432/build?schema=public";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: datasourceUrl,
  },
});
